---
title: "Script used for processing  ex vivo high-throughput data described in Figure 6"
output: html_notebook
---

Load required packages
```{r}
library(ggplot2)
library(flux)

```



Load required functions
```{r}
getBootSample <- function(x, B=100) {
    dif.doses <- length(unique(x[,1]))
    B.fit.y <- matrix(NA, dif.doses, B)
    N <- nrow(x)/dif.doses
    ids.b <- matrix(sample(size=N*dif.doses*B, x=1:N, replace=T), nrow=B)
    for (b in 1:B) {
        b.data <- NULL
        for (k in 1:N) {
            b.data <- c(b.data, ids.b[b,((k-1)*dif.doses+1):
                                          ((k-1)*dif.doses+dif.doses)]
                        + N* (0:(dif.doses-1)))
        }
        b.data <- x[b.data,]
        b.res <-isoreg(x=b.data$x, y=b.data$y)
        b.fit.y <- b.res$yf[seq(from=1, length=dif.doses,
                                by=nrow(b.data)/dif.doses)]
        B.fit.y[,b] <- b.fit.y
    }
    B.fit.y
}
```


Load required data
```{r}

X <- read.csv("/Users/shea01/Documents/PAPERS/Co-clinical trial/Co_clinical_trial/MANUSCRIPT/WIP October 2023/Fig 6/HT drug screen/code to upload/input data.csv", stringsAsFactors=F, header=T)

```


Generate dose response curve fits

```{r}
dataframe <- as.data.frame(table(X$Model, X$Previous_treatment, X$Drug))
dataframe <- dataframe[which(dataframe$Freq>0),]
row.names(dataframe) <- 1:nrow(dataframe)
colnames(dataframe) <- c("Model","Previous_treatment", "Drug")
dataframe$AUC <- NA
dataframe$AUC.LI <- NA
dataframe$AUC.UI <- NA
dataframe$AUC.var <- NA
dataframe$IC50 <- NA
dataframe$IC50.LI <- NA
dataframe$IC50.UI <- NA

mfit <- list()
LI <- list()
UI <- list()

xvalues <- c(0.01, 0.03, 0.10, 0.30, 1.00, 3.00, 10.00)

for (i in 1:nrow(dataframe)) { 
  sub.x <- subset(X, Model==dataframe$Model[i] 
                  & Previous_treatment==dataframe$Previous_treatment[i] 
                  & Drug==dataframe$Drug[i])
  sub.x <- data.frame(x=sub.x$Concentration, y=sub.x$Response)
  sub.x <- sub.x[order(sub.x$x),]
  mfit[[i]] <- isoreg(sub.x)
  bootstrap <- getBootSample(sub.x)
  LI[[i]] <- apply(bootstrap, 1, quantile, p=c(0.025))
  UI[[i]] <- apply(bootstrap, 1, quantile, p=c(0.975))
 
  tmp <- approx(log10(mfit[[i]]$x), mfit[[i]]$yf, n=100)
  IC50 <- 10^(tmp$x[which.min(abs(tmp$y-50))])
  area <- diff(range(log10(mfit[[i]]$x)))*100
  AUC <- auc(log10(mfit[[i]]$x), mfit[[i]]$yf, thresh = NULL, dens = 100, sort.x = TRUE)/area
  dataframe$AUC[i] <- AUC
  dataframe$IC50[i] <- IC50
    AUC.boot.all <- apply(bootstrap, 
                        2, 
                        function(x) {
                          auc(log10(xvalues), x, 
                              thresh = NULL, dens = 100, sort.x = TRUE)/area
                        })
  AUC_LI <- quantile(AUC.boot.all, p=c(0.025))
  AUC_UI <- quantile(AUC.boot.all, p=c(0.975))
  AUC.var <- var(AUC.boot.all) 
  
  dataframe$AUC.LI[i] <- AUC_LI
  dataframe$AUC.UI[i] <- AUC_UI
  dataframe$AUC.var[i] <- AUC.var
  
  IC50.boot.all <- apply(bootstrap, 
                         2, 
                         function(x) {
                           tmp.boot <- (approx(log10(xvalues), x, n=100))
                           10^(tmp.boot$x[which.min(abs(tmp.boot$y-50))])
                         })
  IC50_LI <- quantile(IC50.boot.all, p=c(0.025))
  IC50_UI <- quantile(IC50.boot.all, p=c(0.975))
  dataframe$IC50.LI[i] <- IC50_LI
  dataframe$IC50.UI[i] <- IC50_UI
}

```


Plot AUC values (Figure 6B)

```{r}

ggplot(dataframe) + 
  aes(x=Drug, y=AUC, col=Previous_treatment, ymin=AUC.LI, ymax=AUC.UI) + 
  geom_pointrange(position=position_dodge(width = .8), size=0.2) +
  ggtitle("AUC") + 
  coord_flip() +
  scale_y_continuous(limits=c(0, 1), breaks=c(0, 0.2, 0.4, 0.6, 0.8, 1.0))+
  theme_bw(base_size = 14)+
  xlab("Drugs") +
  labs(colour = "Cohort") +
  scale_color_manual(values=c("#E59F86", "#C83827","#4A9B87","#50BBD2","#8490B2","#000000")) +
  theme(plot.title = element_text(size = 10), 
        axis.title = element_text(size=10),
        axis.text = element_text(size=10),
        legend.text = element_text(size=10),
        legend.title =element_text(size=10)) +
  facet_wrap(~ Model)


```




Plot relevant dose response curves (Figure 6C)

```{r}

par(mfrow=c(2, 2))
i=252
plot(log10(mfit[[i]]$x), mfit[[i]]$yf, 
     type = "l", col="black", 
     ylim = c(0, 100), 
     main = "1040: Olaparib", 
     xlab = "Concentration (uM)", 
     ylab = "Response (%)",
     xaxt = "n")
polygon(c(log10(xvalues), rev(log10(xvalues))), c(UI[[i]], rev(LI[[i]])),
        border = NA, col=rgb(0, 0, 0,0.2))
lines(log10(mfit[[i]]$x), mfit[[i]]$yf, col="black", lwd=2.5)
i=236
polygon(c(log10(xvalues), rev(log10(xvalues))), c(UI[[i]], rev(LI[[i]])),
        border = NA, col=rgb(1, 0, 0,0.2))
lines(log10(mfit[[i]]$x), mfit[[i]]$yf, col="red", lwd=2.5)
axis(1, at=c(-2, -1.5, -1, -0.5, 0, 0.5, 1), labels=c(0.01, 0.03, 0.1, 0.3, 1, 3, 10))
legend("topleft", cex=1, title = "Cohort", c("Untreated","CT"), pch=20, col=c("black", "red"))

i=160
plot(log10(mfit[[i]]$x), mfit[[i]]$yf, 
     type = "l", col="black", 
     ylim = c(0, 100), 
     main = "1040: BMN-673", 
     xlab = "Concentration (uM)", 
     ylab = "Response (%)",
     xaxt = "n")
polygon(c(log10(xvalues), rev(log10(xvalues))), c(UI[[i]], rev(LI[[i]])),
        border = NA, col=rgb(0, 0, 0,0.2))
lines(log10(mfit[[i]]$x), mfit[[i]]$yf, col="black", lwd=2.5)
i=144
polygon(c(log10(xvalues), rev(log10(xvalues))), c(UI[[i]], rev(LI[[i]])),
        border = NA, col=rgb(1, 0, 0,0.2))
lines(log10(mfit[[i]]$x), mfit[[i]]$yf, col="red", lwd=2.5)
axis(1, at=c(-2, -1.5, -1, -0.5, 0, 0.5, 1), labels=c(0.01, 0.03, 0.1, 0.3, 1, 3, 10))
legend("topleft", cex=1, title = "Cohort", c("Untreated","CT"), pch=20, col=c("black", "red"))

i=253
plot(log10(mfit[[i]]$x), mfit[[i]]$yf, 
     type = "l", col="black", 
     ylim = c(0, 100), 
     main = "1141: Olaparib", 
     xlab = "Concentration (uM)", 
     ylab = "Response (%)",
     xaxt = "n")
polygon(c(log10(xvalues), rev(log10(xvalues))), c(UI[[i]], rev(LI[[i]])),
        border = NA, col=rgb(0, 0, 0,0.2))
lines(log10(mfit[[i]]$x), mfit[[i]]$yf, col="black", lwd=2.5)
i=237
polygon(c(log10(xvalues), rev(log10(xvalues))), c(UI[[i]], rev(LI[[i]])),
        border = NA, col=rgb(1, 0, 0,0.2))
lines(log10(mfit[[i]]$x), mfit[[i]]$yf, col="red", lwd=2.5)
axis(1, at=c(-2, -1.5, -1, -0.5, 0, 0.5, 1), labels=c(0.01, 0.03, 0.1, 0.3, 1, 3, 10))
legend("topleft", cex=1, title = "Cohort", c("Untreated","CT"), pch=20, col=c("black", "red"))

i=161
plot(log10(mfit[[i]]$x), mfit[[i]]$yf, 
     type = "l", col="black", 
     ylim = c(0, 100), 
     main = "1141: BMN-673", 
     xlab = "Concentration (uM)", 
     ylab = "Response (%)",
     xaxt = "n")
polygon(c(log10(xvalues), rev(log10(xvalues))), c(UI[[i]], rev(LI[[i]])),
        border = NA, col=rgb(0, 0, 0,0.2))
lines(log10(mfit[[i]]$x), mfit[[i]]$yf, col="black", lwd=2.5)
i=145
polygon(c(log10(xvalues), rev(log10(xvalues))), c(UI[[i]], rev(LI[[i]])),
        border = NA, col=rgb(1, 0, 0,0.2))
lines(log10(mfit[[i]]$x), mfit[[i]]$yf, col="red", lwd=2.5)
axis(1, at=c(-2, -1.5, -1, -0.5, 0, 0.5, 1), labels=c(0.01, 0.03, 0.1, 0.3, 1, 3, 10))
legend("topleft", cex=1, title = "Cohort", c("Untreated","CT"), pch=20, col=c("black", "red"))


```

