mc_cores: 10

scm_balance_graph_k_expand: 100

mcp_heatmap_text_cex: 1.2

mcell_mc2d_K: 60
mcell_mc2d_T_edge: 0.005
mcell_mc2d_max_confu_deg: 4
mcell_mc2d_edge_asym: TRUE
mcell_mc2d_k_expand_inout_factor: NULL
mcell_mc2d_proj_blur: 0.02
mcell_mc2d_K_cellproj: 20


mcell_mc2d_height: 600
mcell_mc2d_width: 600
mcell_mc2d_legend_cex: 1.5
mcell_mc2d_plot_key: FALSE
